from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from functions import DB_functions

class Ui_Security(object):
      
    def ConnectDB(self):
        self.db = DB_functions()
        self.db.initDB()

    def setupUi(self, Security):
        Security.setObjectName("Security")
        Security.setWindowModality(QtCore.Qt.ApplicationModal)
        Security.resize(436, 347)
        self.verticalLayout = QtWidgets.QVBoxLayout(Security)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.comboBox = QtWidgets.QComboBox(Security)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.UserIDlabel = QtWidgets.QLabel(Security)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserIDlabel.setFont(font)
        self.UserIDlabel.setObjectName("UserIDlabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.UserIDlabel)
        self.UserIDlineEdit = QtWidgets.QLineEdit(Security)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserIDlineEdit.setFont(font)
        self.UserIDlineEdit.setObjectName("UserIDlineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.UserIDlineEdit)
        self.Passwordlabel = QtWidgets.QLabel(Security)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Passwordlabel.setFont(font)
        self.Passwordlabel.setObjectName("Passwordlabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Passwordlabel)
        self.PasswordlineEdit = QtWidgets.QLineEdit(Security)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PasswordlineEdit.setFont(font)
        self.PasswordlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordlineEdit.setObjectName("PasswordlineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PasswordlineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LoginpushButton = QtWidgets.QPushButton(Security)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LoginpushButton.setFont(font)
        self.LoginpushButton.setObjectName("LoginpushButton")
        self.horizontalLayout_2.addWidget(self.LoginpushButton)
        self.BorrowDetailspushButton = QtWidgets.QPushButton(Security)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BorrowDetailspushButton.setFont(font)
        self.BorrowDetailspushButton.setIconSize(QtCore.QSize(20, 16))
        self.BorrowDetailspushButton.setObjectName("BorrowDetailspushButton")
        self.horizontalLayout_2.addWidget(self.BorrowDetailspushButton)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.SecurityDisplaylineEdit = QtWidgets.QLineEdit(Security)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SecurityDisplaylineEdit.setFont(font)
        self.SecurityDisplaylineEdit.setReadOnly(True)
        self.SecurityDisplaylineEdit.setObjectName("SecurityDisplaylineEdit")
        self.verticalLayout.addWidget(self.SecurityDisplaylineEdit)
        spacerItem9 = QtWidgets.QSpacerItem(20, 66, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)

        self.LoginpushButton.clicked.connect(self.LoginPressed)
        self.BorrowDetailspushButton.clicked.connect(self.BorrowDetailsPressed)
        
        self.retranslateUi(Security)
        QtCore.QMetaObject.connectSlotsByName(Security)
        

    def retranslateUi(self, Security):
        _translate = QtCore.QCoreApplication.translate
        Security.setWindowTitle(_translate("Security", "Security"))
        self.comboBox.setItemText(0, _translate("Security", "STUDENT"))
        self.comboBox.setItemText(1, _translate("Security", "FACULTY"))
        self.UserIDlabel.setText(_translate("Security", "User ID     :"))
        self.Passwordlabel.setText(_translate("Security", "Password :"))
        self.LoginpushButton.setText(_translate("Security", "Login"))
        self.BorrowDetailspushButton.setText(_translate("Security", "BorrowDetails"))
        self.BorrowDetailspushButton.clicked.connect(self.BorrowDetailsPressed)
        self.LoginpushButton.clicked.connect(self.LoginPressed)
        
    def LoginPressed(self,Sec):
        self.ConnectDB()
        user_id = self.UserIDlineEdit.text()
        password = self.PasswordlineEdit.text()
        user_type = self.comboBox.currentText()
        if user_type == "STUDENT":
            self.SecurityDisplaylineEdit.setText("Student Not allowed to Login")
            return
        
        # Compare these values using password check function
        # 0 -> correct password
        # 1 -> password incorrect
        # 2 -> No student with USN
        # 3 -> No match for entered ID
        self.retValue = self.db.password_check(user_id,password,user_type)
        if self.retValue is 0:
            self.SecurityDisplaylineEdit.setText("Password Correct")
            self.DBMS = QtWidgets.QWidget()
            self.dbmsSS = Ui_DBMS()
            self.dbmsSS.setupUi(self.DBMS)
            self.DBMS.show()
            Security.hide()

        elif self.retValue is 1:
            self.SecurityDisplaylineEdit.setText("Password Incorrect")
            self.PasswordlineEdit.setText("")
        elif self.retValue is 2:
            self.SecurityDisplaylineEdit.setText("No Student with the USN. Enter Valid USN")
            self.PasswordlineEdit.setText("")
        elif self.retValue is 3:
            self.SecurityDisplaylineEdit.setText("No match to the entered ID")
            self.PasswordlineEdit.setText("")
        return


    def BorrowDetailsPressed(self):
        self.ConnectDB()
        self.user_id = self.UserIDlineEdit.text()
        self.password = self.PasswordlineEdit.text()
        self.user_type = self.comboBox.currentText()
        self.retValue = self.db.password_check(self.user_id,self.password,self.user_type)
        if self.retValue is 0:
            self.SecurityDisplaylineEdit.setText("Password Correct")
            self.dispW = QtWidgets.QWidget()
            self.disp = Ui_Form()
            self.disp.setupUi(self.dispW,[3,self.user_id])
            # add a statement to enter the details into the table
            self.dispW.show()
            Security.hide()

        elif self.retValue is 1:
            self.SecurityDisplaylineEdit.setText("Password Incorrect")
            self.PasswordlineEdit.setText("")
        elif self.retValue is 2:
            self.SecurityDisplaylineEdit.setText("No Student with the USN. Enter Valid USN")
            self.PasswordlineEdit.setText("")
        elif self.retValue is 3:
            self.SecurityDisplaylineEdit.setText("No match to the entered ID")
            self.PasswordlineEdit.setText("")
        return
    
class Ui_Form(object):

    def LoadBorrowList(self):
        dbms = sqlite3.connect("DBMS_SS.db")
        result = dbms.execute("SELECT * FROM BORROW")
        self.tableWidget.setRowCount(0)
        self.tableWidget.insertRow(0)
        font = QtGui.QFont()
        font.setBold(True)
        head = ["USN","ICNum","Count"]
        for i in range(3):
            self.tableWidget.setItem(0,i,QtWidgets.QTableWidgetItem(head[i]))
            self.tableWidget.item(0, i).setFont(font)

        for row_num,row_data in enumerate(result):
            self.tableWidget.insertRow(row_num+1)
            for col_num,data in enumerate(row_data):
                self.tableWidget.setItem(row_num+1,col_num,QtWidgets.QTableWidgetItem(str(data)))
        dbms.close()

    def LoadICList(self):
        dbms = sqlite3.connect("DBMS_SS.db")
        result = dbms.execute("SELECT * FROM COMPONENTS")
        self.tableWidget.setRowCount(0)
        self.tableWidget.insertRow(0)
        font = QtGui.QFont()
        font.setBold(True)
        head = ["ICNUM/NAME","COST_INR","Count_AVAILABLE"]
        for i in range(3):
            self.tableWidget.setItem(0,i,QtWidgets.QTableWidgetItem(head[i]))
            self.tableWidget.item(0, i).setFont(font)

        for row_num,row_data in enumerate(result):
            self.tableWidget.insertRow(row_num+1)
            for col_num,data in enumerate(row_data):
                self.tableWidget.setItem(row_num+1,col_num,QtWidgets.QTableWidgetItem(str(data)))
        dbms.close()

    def LoadStList(self):
        dbms = sqlite3.connect("DBMS_SS.db")
        if(dbms.execute("SELECT USER_TYPE FROM SECURITY WHERE SECURITY.USN_ID == ?",(self.Load[1],)).fetchone()[0] == "FACULTY"):
            result = dbms.execute("SELECT * FROM BORROW")
        else:
            result = dbms.execute("SELECT * FROM BORROW WHERE BORROW.STUSN == ?",(self.Load[1],))
        self.tableWidget.setRowCount(0)
        self.tableWidget.insertRow(0)
        font = QtGui.QFont()
        font.setBold(True)
        head = ["USN","ICNum","Count"]
        for i in range(3):
            self.tableWidget.setItem(0,i,QtWidgets.QTableWidgetItem(head[i]))
            self.tableWidget.item(0, i).setFont(font)

        for row_num,row_data in enumerate(result):
            self.tableWidget.insertRow(row_num+1)
            for col_num,data in enumerate(row_data):
                self.tableWidget.setItem(row_num+1,col_num,QtWidgets.QTableWidgetItem(str(data)))
        dbms.close()

    def DispClose(self):
        self.form.hide()
        ui.UserIDlineEdit.setText("")
        ui.PasswordlineEdit.setText("")
        ui.SecurityDisplaylineEdit.setText("")
        if self.Load[0] <= 2:
            ui.DBMS.show()
        else:
            Security.show()
        

    def setupUi(self, Form,load):
        self.form = Form
        self.Load = load
        Form.setObjectName("Display")
        Form.resize(344, 298)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ClosepushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ClosepushButton.setFont(font)
        self.ClosepushButton.setObjectName("ClosepushButton")
        self.horizontalLayout.addWidget(self.ClosepushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        if load[0] == 1:
            self.LoadBorrowList()
        elif load[0] == 2:
            self.LoadICList()
        else:
            self.LoadStList()

        self.ClosepushButton.clicked.connect(self.DispClose)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ClosepushButton.setText(_translate("Form", "CLOSE"))



class Ui_DBMS(object):
    # self := self.dbmsSS from Security.py
    def ConnectDB(self):
        self.db = DB_functions()
        self.db.initDB()

    def setupUi(self, DBMS):
        self.flag = 0
        self.dbmsL = DBMS
        DBMS.setObjectName("DBMS")
        DBMS.resize(662, 543)
        self.formLayout = QtWidgets.QFormLayout(DBMS)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Studentlabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Studentlabel.setFont(font)
        self.Studentlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Studentlabel.setObjectName("Studentlabel")
        self.horizontalLayout_3.addWidget(self.Studentlabel)
        spacerItem = QtWidgets.QSpacerItem(100, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.USNSlabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.USNSlabel.setFont(font)
        self.USNSlabel.setObjectName("USNSlabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.USNSlabel)
        self.USNSlineEdit = QtWidgets.QLineEdit(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.USNSlineEdit.setFont(font)
        self.USNSlineEdit.setObjectName("USNSlineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.USNSlineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.ICNumSlabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ICNumSlabel.setFont(font)
        self.ICNumSlabel.setObjectName("ICNumSlabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ICNumSlabel)
        self.ICNumSlineEdit = QtWidgets.QLineEdit(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ICNumSlineEdit.setFont(font)
        self.ICNumSlineEdit.setObjectName("ICNumSlineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ICNumSlineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.CountSlabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CountSlabel.setFont(font)
        self.CountSlabel.setObjectName("CountSlabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.CountSlabel)
        self.CountSlineEdit = QtWidgets.QLineEdit(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CountSlineEdit.setFont(font)
        self.CountSlineEdit.setObjectName("CountSlineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.CountSlineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BorrowpushButton = QtWidgets.QPushButton(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BorrowpushButton.setFont(font)
        self.BorrowpushButton.setObjectName("BorrowpushButton")
        self.horizontalLayout.addWidget(self.BorrowpushButton)
        self.ReturnpushButton = QtWidgets.QPushButton(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ReturnpushButton.setFont(font)
        self.ReturnpushButton.setObjectName("ReturnpushButton")
        self.horizontalLayout.addWidget(self.ReturnpushButton)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Facultylabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Facultylabel.setFont(font)
        self.Facultylabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Facultylabel.setObjectName("Facultylabel")
        self.horizontalLayout_2.addWidget(self.Facultylabel)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.ICNumFlabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ICNumFlabel.setFont(font)
        self.ICNumFlabel.setObjectName("ICNumFlabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.ICNumFlabel)
        self.ICNumFlineEdit = QtWidgets.QLineEdit(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ICNumFlineEdit.setFont(font)
        self.ICNumFlineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ICNumFlineEdit.setObjectName("ICNumFlineEdit")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.ICNumFlineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(14, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        self.CostFlabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CostFlabel.setFont(font)
        self.CostFlabel.setObjectName("CostFlabel")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.CostFlabel)
        self.CostFlineEdit = QtWidgets.QLineEdit(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CostFlineEdit.setFont(font)
        self.CostFlineEdit.setObjectName("CostFlineEdit")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.CostFlineEdit)
        spacerItem7 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(16, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.CountFlabel = QtWidgets.QLabel(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CountFlabel.setFont(font)
        self.CountFlabel.setObjectName("CountFlabel")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.CountFlabel)
        self.CountFlineEdit = QtWidgets.QLineEdit(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CountFlineEdit.setFont(font)
        self.CountFlineEdit.setObjectName("CountFlineEdit")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.CountFlineEdit)
        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(18, QtWidgets.QFormLayout.FieldRole, spacerItem8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ADDpushButton = QtWidgets.QPushButton(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ADDpushButton.setFont(font)
        self.ADDpushButton.setObjectName("ADDpushButton")
        self.horizontalLayout_4.addWidget(self.ADDpushButton)
        self.RemovepushButton = QtWidgets.QPushButton(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RemovepushButton.setFont(font)
        self.RemovepushButton.setObjectName("RemovepushButton")
        self.horizontalLayout_4.addWidget(self.RemovepushButton)
        self.formLayout.setLayout(20, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(23, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.DisplaylineEdit = QtWidgets.QLineEdit(DBMS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DisplaylineEdit.setFont(font)
        self.DisplaylineEdit.setReadOnly(True)
        self.DisplaylineEdit.setObjectName("DisplaylineEdit")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.SpanningRole, self.DisplaylineEdit)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(21, QtWidgets.QFormLayout.FieldRole, spacerItem10)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LogoutpushButton = QtWidgets.QPushButton(DBMS)
        self.LogoutpushButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LogoutpushButton.setFont(font)
        self.LogoutpushButton.setObjectName("LogoutpushButton")
        self.horizontalLayout_5.addWidget(self.LogoutpushButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.BorrowListpushButton = QtWidgets.QPushButton(DBMS)
        self.BorrowListpushButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BorrowListpushButton.setFont(font)
        self.BorrowListpushButton.setObjectName("BorrowListpushButton")
        self.horizontalLayout_5.addWidget(self.BorrowListpushButton)
        self.ICListpushButton = QtWidgets.QPushButton(DBMS)
        self.ICListpushButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ICListpushButton.setFont(font)
        self.ICListpushButton.setObjectName("ICListpushButton")
        self.horizontalLayout_5.addWidget(self.ICListpushButton)
        self.formLayout.setLayout(24, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_5)

        self.BorrowpushButton.clicked.connect(self.BorrowPressed)
        self.ReturnpushButton.clicked.connect(self.ReturnPressed)
        self.ADDpushButton.clicked.connect(self.ADDPressed)
        self.RemovepushButton.clicked.connect(self.RemovePressed)
        self.LogoutpushButton.clicked.connect(self.LogoutPressed)
        self.BorrowListpushButton.clicked.connect(self.BorrowListPushed)
        self.ICListpushButton.clicked.connect(self.ICListPressed)
        
        self.retranslateUi(DBMS)
        QtCore.QMetaObject.connectSlotsByName(DBMS)

    def retranslateUi(self, DBMS):
        _translate = QtCore.QCoreApplication.translate
        DBMS.setWindowTitle(_translate("DBMS", "DBMS"))
        self.Studentlabel.setText(_translate("DBMS", "Student"))
        self.USNSlabel.setText(_translate("DBMS", "USN             :"))
        self.ICNumSlabel.setText(_translate("DBMS", "ICNum        :"))
        self.CountSlabel.setText(_translate("DBMS", "Count        :"))
        self.BorrowpushButton.setText(_translate("DBMS", "Borrow"))
        self.ReturnpushButton.setText(_translate("DBMS", "Return"))
        self.Facultylabel.setText(_translate("DBMS", "Faculty"))
        self.ICNumFlabel.setText(_translate("DBMS", "ICNum       : "))
        self.CostFlabel.setText(_translate("DBMS", "Cost          :"))
        self.CountFlabel.setText(_translate("DBMS", "Count        :"))
        self.ADDpushButton.setText(_translate("DBMS", "ADD"))
        self.RemovepushButton.setText(_translate("DBMS", "Remove"))
        self.LogoutpushButton.setText(_translate("DBMS", "Logout"))
        self.BorrowListpushButton.setText(_translate("DBMS", "Borrow List"))
        self.ICListpushButton.setText(_translate("DBMS", "IC List"))


    def BorrowPressed(self):
        self.ConnectDB()
        self.usnS = self.USNSlineEdit.text()
        self.icnumS = self.ICNumSlineEdit.text()
        self.countS = int(self.CountSlineEdit.text())
        self.retValue = self.db.borrow(self.usnS,self.icnumS,self.countS)
        self.DisplaylineEdit.setText(self.retValue)

    def ReturnPressed(self):
        self.ConnectDB()
        self.usnS = self.USNSlineEdit.text()
        self.icnumS = self.ICNumSlineEdit.text()
        self.countS = int(self.CountSlineEdit.text())
        self.retValue = self.db.return_ic(self.usnS,self.icnumS,self.countS)
        self.DisplaylineEdit.setText(self.retValue)

    def ADDPressed(self):
        self.ConnectDB()
        self.icnumF = self.ICNumFlineEdit.text()
        self.costF = self.CostFlineEdit.text()
        self.countF = int(self.CountFlineEdit.text())
        self.retValue = self.db.add_component(self.icnumF,self.costF,self.countF)
        self.DisplaylineEdit.setText(self.retValue)

    def RemovePressed(self):
        self.ConnectDB()
        self.icnumF = self.ICNumFlineEdit.text()
        self.costF = self.CostFlineEdit.text()
        self.countF = int(self.CountFlineEdit.text())
        self.retValue = self.db.remove_component(self.icnumF,self.costF,self.countF)
        self.DisplaylineEdit.setText(self.retValue)

    def LogoutPressed(self):
        self.dbmsL.hide()
        ui.UserIDlineEdit.setText("")
        ui.PasswordlineEdit.setText("")
        ui.SecurityDisplaylineEdit.setText("")
        Security.show()        

    def BorrowListPushed(self):
        self.dispW = QtWidgets.QWidget()
        self.disp = Ui_Form()
        self.disp.setupUi(self.dispW,[1])
        self.dispW.show()
        self.dbmsL.hide()
        return
 
    def ICListPressed(self):
        self.dispW = QtWidgets.QWidget()
        self.disp = Ui_Form()
        self.disp.setupUi(self.dispW,[2])
        self.dispW.show()
        self.dbmsL.hide()
        return


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Security = QtWidgets.QWidget()
    ui = Ui_Security()
    ui.setupUi(Security)
    Security.show()
    sys.exit(app.exec_())

